[workspace]
resolver = "2"
members = ["milli", "filter-parser", "flatten-serde-json", "json-depth-checker", "benchmarks", "cli"]
default-members = ["milli"]

[profile.dev]
opt-level = 3

[profile.release]
debug = true
codegen-units = 1

# Make sure that the build scripts and proc-macros are compiled with
# all the optimizations. It speeds up the zip crate that we use in the build.rs.
[profile.dev.build-override]
opt-level = 3
[profile.release.build-override]
opt-level = 3
[profile.bench.build-override]
opt-level = 3
[profile.test.build-override]
opt-level = 3
